import numpy as np
import networkx as nx
from pyvis.network import Network

#============================================================
def GenerateMatrix():

    n_nodes=int(input("-Number of Nodes: "))
    print('\n-Build the Adjacency Matrix Row by Row: ')
    adjacencyMatrix=np.zeros((n_nodes,n_nodes))
    for i in range(0,n_nodes):
        print('\n-',i+1,'row: ')
        adjacencyMatrix[i]=list(map(int, input().split()))
    print(adjacencyMatrix)
    return adjacencyMatrix
#============================================================


#============================================================
def CanonicalNetwork(n_nodes=100,link_prob=0.1):
#Adjacency Matrix Generation
    adjacencyMatrix=np.zeros((n_nodes,n_nodes))
    for i in range(0,n_nodes):
        for j in range(0,n_nodes):
            if np.random.default_rng().random() <= link_prob:
               adjacencyMatrix[i,j]=1
            else: adjacencyMatrix[i,j]=0
    return adjacencyMatrix
#============================================================


#============================================================
def RandomNetwork(n_nodes=100):
    """
    This function generates a random adjacency matrix of a network with
    'n_nodes' nodes. The links between the nodes are random.

    Parameters
    ----------
    n_nodes : int, optional
        Set the number of nodes of the network. The default is 100.

    Returns
    -------
    Returns a numpy array.

    """
#Adjacency Matrix Generation
    adjacencyMatrix = np.random.rand(n_nodes,n_nodes)
    for i in range(0,n_nodes):
        for j in range(0,n_nodes):
            adjacencyMatrix[i,j]=np.round(adjacencyMatrix[i,j])
    return adjacencyMatrix
#============================================================


#============================================================
def NetworkVisualization(adjacencyMatrix,Directed=True,
                         px_X='900',px_Y='600',
                         network_name="NetworkPlot.html"):
    """
    This function generates an HTML file in which is plotted the
    network created.
    
    Parameters
    ----------
    adjacencyMatrix : ndarray
        Insert a squared NumPy array of real numbers.
    Directed : bool, optional
        Specifies if the Network has to be visualized as directed (True)
        or undirected (False). The default value is True.
    px_X : string, optional
        Set the number of pixels on the X-Axis; must be given as a string.
        The default value is '900'.
    px_Y : string, optional
        Set the number of pixels on the Y-Axis; must be given as a string.
        The default value is '600'.
    network_name : string, optional
        Set the name of the HTML file generated by the function.
        The default name is "NetworkPlot.html".
    
    Returns
    -------
    This function returns nothing, but it generates an HTML file inside the
    working directory.

    Examples
    --------
    >>> test_array=np.array([[0,1,1,1,1],[1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0]])
    [[0,1,1,1,1],
     [1,0,0,0,0],
     [1,0,0,0,0],
     [1,0,0,0,0],
     [1,0,0,0,0]]
    >>> NetworkVisualization(test_array,network_name="New Network Plot!")
    
    >>> test_array=np.array([[0,1.3,0],[0,0,0.3],[4,0,0]])
    [[0,1.3,0],
     [0,0,0.3],
     [4,0,0.1]]
    >>> NetworkVisualization(test_array,Directed=False,px_X='600')
    
    >>> test_array=np.random.default_rng()
    >>> test_array.integers(2, size=(100, 100))
    random 100x100 array of zeros and ones
    >>> NetworkVisualization(test_array,px_X='1000',px_Y='1200')
    """
    node_number=adjacencyMatrix.shape[1]
    
    if Directed == True:
        NX_Network=nx.DiGraph(adjacencyMatrix)
        pyvis_net=Network(notebook=True,directed=True,height=px_Y+'px', 
                          width=px_X+'px')
        pyvis_net.from_nx(NX_Network,default_node_size=node_number)
        pyvis_net.hrepulsion(node_distance=300)
        pyvis_net.show_buttons()
        pyvis_net.show(network_name)
    else:
        NX_Network=nx.Graph(adjacencyMatrix)
        pyvis_net=Network(notebook=True,directed=False,height=px_Y, 
                          width=px_X)
        pyvis_net.from_nx(NX_Network,default_node_size=node_number)
        pyvis_net.hrepulsion(node_distance=300)
        pyvis_net.show_buttons()
        pyvis_net.show(network_name)
#============================================================

NetworkVisualization(CanonicalNetwork(100,0.05))
